modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="create_filtering_filter"
version="\${version}"
displayName="Create: Filtering Filter"
authors="Aether_254"
description='''Adds a Create filter dedicated to matching filter items directly, with optional internal-data comparison.'''

[[dependencies.create_filtering_filter]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_filtering_filter]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.create_filtering_filter]]
modId="create"
type="required"
versionRange="[6.0.11,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_filtering_filter]]
modId="cloth_config"
type="required"
versionRange="[15.0.140,)"
ordering="AFTER"
side="BOTH"

